[package]
name = "rocksdb-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
rocksdb = { version = "0.19", features = ["multi-threaded-cf", "zstd", "lz4", "jemalloc"], default-features = false }
