[package]
name = "weedb"
version = "0.2.2"
edition = "2021"
description = "A thin wrapper around RocksDB."
authors = ["Rexagon", "0xdeafbeef"]
repository = "https://github.com/broxus/weedb"
rust-version = "1.66.1"
include = ["src/**/*.rs", "benches/**/*.rs", "LICENSE-*", "README.md"]
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0"
tracing = "0.1"
metrics = { version = "0.22.3", optional = true }

librocksdb-sys = "0.16.0"
rocksdb = { version = "0.22.0", features = ["multi-threaded-cf"], default-features = false }

[features]
default = ["zstd", "lz4", "jemalloc", "metrics"]
zstd = ["rocksdb/zstd"]
lz4 = ["rocksdb/lz4"]
jemalloc = ["rocksdb/jemalloc"]
metrics = ["dep:metrics"]
